{
  "hash": "9456dbf30b4b5eb3ed1f5ba08d355f16",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelling differences between groups: Part 1 (of 2)\"\nsubtitle: \"BIOL2022 - L03b-alt\"\nrevealjs-plugins:\n  - solarized-pdf\nauthor:\n  - name: Dr Januar Harianto\n    affiliations: The University of Sydney\nembed-resources: false # embed resources into single HTML file -- enable when ready to publish\n# NOTE: please check _quarto.yml file for more options\nexecute: \n  echo: false\ncode-fold: true\n---\n\n\n\n\n\n## Learning objectives\n\nBy the end of this lecture, you should be able to:\n\n- [ ] identify whether a study involves a reference value, independent groups, or paired measurements;\n- [ ] decide which comparison of means is appropriate for the study design;\n- [ ] use a linear model, where useful, to describe that comparison; and\n- [ ] assess and interpret the result.\n\n# When is a difference in means meaningful?\n\n##\n\n![](../../assets/gentoo.jpeg){fig-alt=\"\"}\n\n::: fragment\n> Do male and female Gentoo penguins differ in body mass?\n:::\n\n##\n\n:::: {.columns}\n:::: {.column width=\"50%\"}\n\n\n![[Source](https://www.illawarramercury.com.au/story/8727623/most-baby-foods-fail-health-test-make-dodgy-claims/)](assets/dodgy-food.png){fig-align=\"left\"}\n::::\n:::: {.column width=\"50%\"}\n![](assets/smiling-tums-nutrition.jpg){width=\"100%\" fig-alt=\"Nutrition-information panel for Smiling Tums Apple and Banana with Oats. It lists sugars as 7.7 grams per 100 grams.\"}\n::::\n:::::\n\n\n>  Is the sugar content (7.7 g per 100 g) of this particular baby food product different from that advertised?\n\n\n## [TL;DR](https://en.wikipedia.org/wiki/TL;DR)\n\n- Often, we see patterns that clearly show differences from expectations, or between groups. \n- The ***t*-test** allows us to quantify these differences and determine if they are **statistically significant**.\n\n. . . \n\nWe may compare:\n\n- a sample mean with a reference value;\n- mean values from two independent groups; or\n- mean values from paired measurements.\n\n. . .\n\nIn each case, we ask whether the observed **differences** are simply because sample vary.\n\n. . .\n\n**But really, these are general linear models (GLMs) but with either no predictor or binary predictors.** The slope and intercept are simply derived from \"two\" values.\n\n\n\n## History and context\n::: columns\n::: {.column width=\"40%\"}\n![[William Sealy Gosset](https://en.wikipedia.org/wiki/William_Sealy_Gosset) (1876-1937)](assets/will.png){fig-align=\"left\"}\n:::\n::: {.column width=\"60%\"}\n\n> Fisher would have discovered it anyway...\n\n-- *on his invention of the t-statistic and the t-distribution*\n\n::: fragment\n- A statistician at Guinness Brewery.\n- Developed the *t*-test to monitor the quality of stout (beer), **by comparing barley yields**.\n:::\n:::\n:::\n\n\n\n# The *t*-distribution\n\n\n## Normal distribution and the *t*-distribution\n\n:::: {.columns}\n::: {.column width=\"32%\"}\n\nBoth distributions are centred on zero.\n\nThe *t*-distribution is:\n\n- lower in the middle; and\n- heavier in the tails.\n\n:::\n::: {.column width=\"68%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n:::\n::::\n\n\n## As sample size increases, the *t*-distribution approaches normality\n\n::::: {.columns}\n:::: {.column width=\"32%\"}\n\nSmaller samples produce heavier tails because there is more uncertainty when variation is estimated from the data.\n\n::::\n:::: {.column width=\"68%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n::::\n:::::\n\n## The *t*-statistic compares a difference with its uncertainty\n\n$$\nt = \\frac{\\text{Signal}}{\\text{Noise}}\n$$\n\n- **Signal:** the observed difference of interest, such as a difference between group means.\n- **Noise:** the uncertainty around that difference.\n\nA large absolute value of *t* means that the observed difference is large relative to the uncertainty in the estimate.\n\n## In practice...\n\nIt is more simple than that. Simply identify the two groups of interest and most modern software will do the rest.\n\n::: columns\n::: {.column width=\"50%\"}\n### One-sample *t*-test\n\n\nAre penguin bill lengths different from 40 mm?\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata(penguins)\nt.test(penguins$bill_length_mm, mu = 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  penguins$bill_length_mm\nt = 13.285, df = 341, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 40\n95 percent confidence interval:\n 43.34125 44.50261\nsample estimates:\nmean of x \n 43.92193 \n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n### Two-sample *t*-test\n\nIs bill length different between Male and Female penguins?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nt.test(bill_length_mm ~ sex, var.equal = TRUE, data = penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  bill_length_mm by sex\nt = -6.667, df = 331, p-value = 1.094e-10\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -4.866557 -2.649027\nsample estimates:\nmean in group female   mean in group male \n            42.09697             45.85476 \n```\n\n\n:::\n:::\n\n:::\n:::\n\n\n\n# Modelling the *t*-test\n\n## Model-centric approach\n\nThe *t*-test is a special case of the GLM because it can be considered a linear model, but the predictors are **binary** (two categories in a two-sample *t*-test), or **absent** (one-sample *t*-test or paired *t*-test) rather than continuous. \n\n So, given that $$ \\text{response} \\sim \\text{predictor} $$ then for the **two-sample *t*-test**, the model is $$ \\text{response} = \\beta_0 + \\beta_1 \\cdot \\text{predictor} + \\epsilon $$\n\nand for a **one-sample or paired *t*-test**, the model is $$ \\text{response} = \\beta_0 + \\epsilon $$ \n\n::: fragment\nEssentially, we need to understand that $\\beta_1$ is the difference between the two groups, and $\\beta_0$ is the mean of the first group.\n:::\n\n\n\n# One-sample *t*-test\n\n## The question\n\nAre mean penguin bill lengths in my sample (blue line) different from 40 mm (red line)?\n\n### One-sample *t*-test\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Modelling the one-sample *t*-test\n\n- **Response**: bill length\n- **Predictor**: none, instead we test whether the response is equal to a known value (intercept).\n\n### The model\nBill length is defined by a mean of 40 mm: $$ \\text{bill length} \\sim 40 $$\n\n\n\n## Modelling the one-sample *t*-test\n\nWe generally need to subtract the known value from the response variable such that:\n\n$$ \\text{bill\\_length\\_mm} - 40 \\sim 0 $$\n\n\n### In R\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm - 40 ~ 1, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.8219  -4.6969   0.5281   4.5781  15.6781 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.9219     0.2952   13.29   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.46 on 341 degrees of freedom\n  (2 observations deleted due to missingness)\n```\n\n\n:::\n:::\n\n\n## Modelling the one-sample *t*-test\n\nWe generally need to subtract the known value from the response variable such that:\n\n$$ \\text{bill\\_length\\_mm} - 40 \\sim 0 $$\n\n\n### In Jamovi\n\nYou will need to double-click on the variable name and transform it to `$source-40`, then use the new variable in the analysis.\n\n![](assets/jamovi-transform-one-sample.png)\n\n:::: fragment\nThe one-sample *t*-test is also one of the few cases where it is probably easier to use the traditional approach. So think of this exercise as a way to understand the GLM approach (and proof that it applies).\n::::\n\n## Assumptions of the one-sample *t*-test\n\nFor the one-sample *t*-test, the only assumption is that the residuals are normally distributed. Under the GLM framework, we can check this by looking at the QQ-plot of the residuals.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\nThe residuals show that the data does not meet the assumption of normality, but the model is robust to this violation as long as the sample size is large and the samples are representative of the population.\n\n## Assumptions of the one-sample *t*-test\n\nWe can also just plot the raw data in the traditional way to check for normality, since there is only one group of data to plot.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\nThe patterns are identical since there are no predictors in the model.\n\n## Interpretation\n\n::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  penguins$bill_length_mm\nt = 13.285, df = 341, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 40\n95 percent confidence interval:\n 43.34125 44.50261\nsample estimates:\nmean of x \n 43.92193 \n```\n\n\n:::\n:::\n\n\n:::\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm - 40 ~ 1, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.8219  -4.6969   0.5281   4.5781  15.6781 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.9219     0.2952   13.29   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.46 on 341 degrees of freedom\n  (2 observations deleted due to missingness)\n```\n\n\n:::\n:::\n\n:::\n\n:::\n\nNotice the similarities and differences between the two approaches.\n\n## Reporting\n\n::: fragment\n### Methods\nA **one-sample t-test** was conducted to determine whether the mean bill length of penguins significantly differed from a hypothesised mean of 40 mm. The analysis was conducted using R version 4.4.0 (R Core Team, 2024) with the `t.test()` function. The assumption of normality was checked visually by examining the QQ-plot of the raw data. This assumption was not met, but the *t*-test was considered robust due to the large sample size and representativeness of the data and was therefore reported.\n\n\n### Results\nThe analysis revealed a statistically significant difference, with the mean bill length (43.9 mm) being significantly greater than 40 mm (t = 13.29 , df = 341, p < 0.01). The 95% confidence interval for the mean bill length was [43.34, 44.50] mm.\n:::\n\n## Reporting\n\n### Methods\nA **general linear model (GLM)** ~~equivalent to a one-sample t-test~~ was performed to determine whether the mean bill length of penguins differed from a hypothesised value of 40 mm. The analysis was conducted using R version 4.4.0 (R Core Team, 2024), with the model specified as:  $$\\text{bill\\_length\\_mm} - 40 \\sim 1$$ where the intercept represents the difference between the mean bill length and 40 mm. The assumption of normality was checked visually by examining the QQ-plot of the residuals. This assumption was not met, but the model was considered robust due to the large sample size and representativeness of the data.\n\n\n### Results\nThe results indicated that the mean difference in bill length from 40 mm was statistically significant. The mean bill length was estimated to be 3.92 mm greater than 40 mm, with a standard error of 0.30 mm (GLM, t = 13.29, df = 341,  p < 0.001). \n\n\n\n# Two-sample *t*-test\n\n## The question\n\nAre the mean bill lengths between male and female penguins different? ***If they are not, then both groups should have the same mean (dotted line).***\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n## Modelling the two-sample *t*-test\n\n- **Response**: bill length\n- **Predictor**: sex\n\n### The model\n\nBill length is a function of sex:\n\n$$ \\text{bill length} \\sim \\text{sex} $$\n\n## Modelling the two-sample *t*-test\n\nThe model specification is more straightforward since a predictor is present: \n$$ \\text{bill\\_length\\_mm} \\sim \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ sex, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.2548  -4.7548   0.8452   4.3030  15.9030 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  42.0970     0.4003 105.152  < 2e-16 ***\nsexmale       3.7578     0.5636   6.667 1.09e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.143 on 331 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.1184,\tAdjusted R-squared:  0.1157 \nF-statistic: 44.45 on 1 and 331 DF,  p-value: 1.094e-10\n```\n\n\n:::\n:::\n\n\n## Assumptions of the two-sample *t*-test: LINE\n\n### If we were to use the traditional *t*-test approach\n\n- Divide the data into the two groups: male and female\n- Check the normality and equal variances of the residuals for each group\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n## Assumptions of the two-sample *t*-test: LINE\n\n### If we were to use the traditional *t*-test approach\n\n- Divide the data into the two groups: male and female\n- Check the normality and equal variances of the residuals for each group\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n## Assumptions of the two-sample *t*-test: LINE\n\n### GLM approach\n\nView the residuals of the model; no need to divide the data\n\n::: fragment\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n:::\n\n## Interpretation\n\n::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  bill_length_mm by sex\nt = -6.667, df = 331, p-value = 1.094e-10\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -4.866557 -2.649027\nsample estimates:\nmean in group female   mean in group male \n            42.09697             45.85476 \n```\n\n\n:::\n:::\n\n:::\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ sex, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.2548  -4.7548   0.8452   4.3030  15.9030 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  42.0970     0.4003 105.152  < 2e-16 ***\nsexmale       3.7578     0.5636   6.667 1.09e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.143 on 331 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.1184,\tAdjusted R-squared:  0.1157 \nF-statistic: 44.45 on 1 and 331 DF,  p-value: 1.094e-10\n```\n\n\n:::\n:::\n\n:::\n:::\n\nSuggestion: paste the results into ChatGPT and ask for a summary.\n\n## What if the assumptions are violated?\n\n1. **Normality**: the *t*-test is robust to violations of normality, especially with large sample sizes. However we can consider transforming the data or using a non-parametric test such as the Wilcoxon rank-sum test if the data is highly skewed.\n2. **Equal variances**: transforming the data can help, but we can consider Welch's *t*-test, which does not assume equal variances, as a viable alternative. Note: there is a [GLM approach](https://stats.stackexchange.com/questions/142685/equivalent-to-welchs-t-test-in-gls-framework) to this but it is complex, so we will not cover it here.\n\n# Paired *t*-test\n\n## First, about related (or paired) samples\n\n- **Related samples** are those where the measurements are taken from the same individual or object at different times or under different conditions: \n  - before and after treatment, \n  - left and right eyes, \n  - two different methods of measurement of the same subject, etc.\n- This causes the measurements to be **dependent** on each other.\n- There is correlation or covariance between the measurements, therefore we use the difference between the measurements as the response variable rather than the measurements separately.\n\nThis is one of the few cases where the **independence** assumption matters and can result in using a paired *t*-test instead of a two-sample *t*-test.\n\n## The question\n\nIs sleep duration different before and after treatment? [Student's sleep data](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/sleep.html), where the same 10 patients were observed for two weeks, with the first week being a control week and the second week being a treatment week.\n\n### Modelling the question\n\n- **Response**: sleep duration\n- **Predictor**: week\n\n### The model\n\nSleep duration is a function of the week:\n\n$$ \\text{sleep duration} \\sim \\text{week} $$\n\n## Modelling the paired *t*-test\n\nWe need to subtract the sleep duration in the control week from the sleep duration in the treatment week such that: $$ \\text{sleep duration (treatment)} - \\text{sleep duration (control)} \\sim 0 $$\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = treatment - control ~ 1)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -1.58  -0.53  -0.28   0.12   3.02 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)    1.580      0.389   4.062  0.00283 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.23 on 9 degrees of freedom\n```\n\n\n:::\n:::\n\n\n## Assumptions of the paired *t*-test\n\nBecause the data is paired, variances should be equal and do not need to be checked, although unequal variances highlight possible issues with the data. \n\n**Otherwise, only the normality assumption needs to be checked.**\n\nWe will not check the assumptions here, since the process remains the same.\n\n\n## Further thinking\n\n- The GLM approach means that the model *just so happens* to match a *particular* traditional test.\n- Interpretation of the model can change as soon as the **structure** of any of the variables change.\n\n::: fragment\n### Example: *t*-test vs. ANOVA\n\nThe two-sample *t*-test can be extended to a **one-way ANOVA** if we have more than two groups to compare. The model remains the same, but the interpretation changes! $$ \\text{response} = \\beta_0 + \\beta_1 \\cdot \\text{predictor} + \\epsilon $$\n\nWe will cover this in great detail next week.\n:::\n\n## Questions to consider\n\n- What are the assumptions of the one-sample *t*-test, two-sample *t*-test, and paired *t*-test? Are they the same?\n- How do you interpret the results of a GLM compared to a traditional *t*-test?\n- What are the advantages and disadvantages of using the GLM approach over the traditional approach?\n\n# Thanks\n\nThis presentation is based on the [SOLES Quarto reveal.js template](https://github.com/usyd-soles-edu/soles-revealjs) and is licensed under a [Creative Commons Attribution 4.0 International License][cc-by].\n\n\n<!-- Links -->\n[cc-by]: http://creativecommons.org/licenses/by/4.0/\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}