{
  "hash": "373d02d2b9acbef0646d0c0744cb4403",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modelling multiple differences: a linear model with two or more categorical $X$ variables\"\nsubtitle: \"BIOL2022\"\nauthor:\n  - name: Dr Januar Harianto\n    affiliations: The University of Sydney\nembed-resources: false # embed resources into single HTML file -- enable when ready to publish\n# NOTE: please check _quarto.yml file for more options\nformat:\n  ochre-revealjs: default\n---\n\n\n\n\n\n# Learning objectives\n\nYou should:\n\n- [ ] Frame ANOVA as a specific application of the General Linear Model (GLM) for categorical predictors.\n- [ ] Formulate a GLM to test for differences between two or more group means.\n- [ ] Explain how an ANOVA summary partitions the variance of a GLM with categorical predictors.\n- [ ] Interpret main effects and interaction terms for categorical predictors within a GLM framework.\n- [ ] Use post-hoc tests to probe significant main effects and interactions in a GLM.\n- [ ] Visualize and interpret the results from a GLM with categorical predictors using interaction plots.\n\n# Analysis of variance (ANOVA)\n\n> It is better to solve the right problem approximately than to solve the *wrong* problem exactly.\n\n— [John Tukey](https://en.wikipedia.org/wiki/John_Tukey) (1915-2000)\n\n## The ANOVA model\nANOVA is a type of linear regression that uses **categorical** predictors.\n\n::: fragment\n### How it works (GLM perspective)\n:::incremental\n1. Fit a linear model using dummy variables for the categories.\n2. Split the total variation in the response variable into:\n    - Variation *between* groups (explained by the model).\n    - Variation *within* groups (unexplained, or residual).\n3. Compare these to test if the differences between groups are greater than the variation within groups.\n:::\n:::\n\n\n## Variation between groups\n\nCan we explain the variation in body mass by species (i.e. **are the means different**)?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/means_plot-1.png){width=960}\n:::\n:::\n\n\n\n## Variation within groups\n\nCan we explain the variation in body mass by an overall mean (i.e. **are they all the same**)?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/p2_plot-1.png){width=960}\n:::\n:::\n\n\n\n## Another way to look at it\n\nAre the distributions of body mass different enough to be considered separate?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/density_ridges-1.png){width=960}\n:::\n:::\n\n\n## Modelling the relationship\n\nFor a GLM: $$ \\text{body mass} = \\beta_0 + \\beta_1 \\cdot \\text{species} + \\epsilon $$ \n\nOnce we use an ANOVA summary to process the model, we get:\n\n$$ \\text{body mass} = \\text{mean} + \\text{species effect (i.e. difference)} + \\epsilon $$\n\nThat is:\n\n- $\\beta_0$ is the **overall mean** of body mass.\n- $\\beta_1$ is the **difference** in body mass between species.\n- We can add the mean to each species effect to get the **estimated body mass** for each species.\n\n\n# Example\n\n![](assets/cartoon-penguins.png)\n\nAre species and sex significant predictors of body mass in penguins?\n\n## First, the general linear model {auto-animate=true}\n\n$$ \\text{body mass} \\sim \\text{species} + \\text{sex} $$\n\n### The interaction term\n\nBecause we are interested in both predictor variables, we include an **interaction term**:\n\n\n$$ \\text{body mass} \\sim \\text{species} \\times \\text{sex} $$\n\n::: fragment\n### Four steps (as always), with a [post-hoc](https://en.wikipedia.org/wiki/Post_hoc_analysis)\n1. **Fit the model**, but do not interpret yet. Visualise the relationship (if possible).\n2. **Check assumptions** from diagnostic plots (residuals).\n3. Select a different model or transform data if assumptions are violated, go back to (2). Skip if assumptions are met.\n4. **Interpret** the model **✨and post-hoc✨**.\n:::\n\n\n## 1. Model/plot {auto-animate=true}\n\n$$ \\text{body mass} \\sim \\text{species} \\times \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/pbox_plot-1.png){width=960}\n:::\n:::\n\n\nSide note: [Beyond bar and box plots](https://z3tt.github.io/beyond-bar-and-box-plots/)\n\n\n## 2. Check assumptions\n$$ \\text{body mass} \\sim \\text{species} \\times \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/fit_diagnostics-1.png){width=960}\n:::\n:::\n\n\n- We see clusters of residuals, a total of 6, representing the 6 combinations of **species $\\times$ sex**.\n- Interpretation of the residuals is as normal: just think of **LINE**!\n\n\n## 2. Check assumptions\n$$ \\text{body mass} \\sim \\text{species} \\times \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/check_model-1.png){width=960}\n:::\n:::\n\n\n\n\n## 4. Interpret\n\nIn practice, if we are interested in comparing means, the **ANOVA summary** table is the most useful.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: body_mass_g\n             Df    Sum Sq  Mean Sq F value    Pr(>F)    \nspecies       2 145190219 72595110 758.358 < 2.2e-16 ***\nsex           1  37090262 37090262 387.460 < 2.2e-16 ***\nspecies:sex   2   1676557   838278   8.757 0.0001973 ***\nResiduals   327  31302628    95727                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThere are **significant interactions**, so we no longer interpret the main effects. **Interpret the interaction term instead.**\n\n\n## Interpreting interactions\n\nWe want to check two things:\n\n- Whether the relationship between body mass and species is dependent on **sex**, and/or\n- Whether the relationship between body mass and sex is dependent on **species**.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/emmip_plots-1.png){width=960}\n:::\n:::\n\n\n\n\n## Interpreting interactions\n\n- Species affects the relationship between body mass and sex. Males are generally heavier than females, but the difference is less pronounced in Chinstrap penguins as seen by the flatter slope compared to the other two species.\n- Sex also affects the relationship between body mass and species. Adelie males are generally heavier than Chinstrap males, but in females it is the opposite: Adelie females are generally lighter than Chinstrap females.\n\n## What if we look at the non-ANOVA summary?\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = body_mass_g ~ species * sex, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-827.21 -213.97   11.03  206.51  861.03 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               3368.84      36.21  93.030  < 2e-16 ***\nspeciesChinstrap           158.37      64.24   2.465  0.01420 *  \nspeciesGentoo             1310.91      54.42  24.088  < 2e-16 ***\nsexmale                    674.66      51.21  13.174  < 2e-16 ***\nspeciesChinstrap:sexmale  -262.89      90.85  -2.894  0.00406 ** \nspeciesGentoo:sexmale      130.44      76.44   1.706  0.08886 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 309.4 on 327 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.8546,\tAdjusted R-squared:  0.8524 \nF-statistic: 384.3 on 5 and 327 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n# Example 2\n\n![](assets/gentoo.jpeg)\n\nAre species and sex significant predictors of bill length in penguins?\n\n## 1. Model/plot {auto-animate=true}\n\n$$ \\text{bill length} \\sim \\text{species} \\times \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/bill_boxplot-1.png){width=960}\n:::\n:::\n\n\n## 2. Check assumptions\n\n$$ \\text{bill length} \\sim \\text{species} \\times \\text{sex} $$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/fit2_diagnostics-1.png){width=960}\n:::\n:::\n\n\n## 4. Interpret\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: bill_length_mm\n             Df Sum Sq Mean Sq  F value Pr(>F)    \nspecies       2 7015.4  3507.7 654.1894 <2e-16 ***\nsex           1 1135.7  1135.7 211.8066 <2e-16 ***\nspecies:sex   2   24.5    12.2   2.2841 0.1035    \nResiduals   327 1753.3     5.4                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nNo significant interactions, **so we can interpret the main effects**.\n\n- The results revealed significant main effects for both species and sex. \n- Specifically, the effect of species on bill length was statistically significant, F(2, 327) = 654.19, p < .001, indicating that bill length varies significantly across different species. \n- The effect of sex was also significant, F(1, 327) = 211.81, p < .001, suggesting that bill length differs between males and females.\n\n\n## 4. Post-hoc\n\nTo further investigate where the differences lie, we can perform a post-hoc test. The most common post-hoc is the Tukey HSD test (honestly significant difference), which can be performed using estimated marginal means (often referred to as emmeans). \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n species   emmean    SE  df lower.CL upper.CL\n Adelie      38.8 0.192 327     38.4     39.2\n Chinstrap   48.8 0.281 327     48.3     49.4\n Gentoo      47.5 0.212 327     47.1     47.9\n\nResults are averaged over the levels of: sex \nConfidence level used: 0.95 \n\n$contrasts\n contrast           estimate    SE  df t.ratio p.value\n Adelie - Chinstrap   -10.01 0.340 327 -29.444 <0.0001\n Adelie - Gentoo       -8.69 0.286 327 -30.398 <0.0001\n Chinstrap - Gentoo     1.32 0.352 327   3.735  0.0006\n\nResults are averaged over the levels of: sex \nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\n##\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/plot_emm_sp-1.png){width=960}\n:::\n:::\n\n\nPost-hoc tests revealed that Chinstrap penguins had significantly longer mean bill lengths (48.8 mm $\\pm$ 0.28 SE) compared to Adelie (38.8 mm $\\pm$ 0.19 SE) and Gentoo penguins (47.5 mm $\\pm$ 0.21 SE), and that all pairwise comparisons were statistically significant (p < .001).\n\n\n## Questions to consider\n\n- When is it more appropriate to summarise a GLM with an ANOVA table versus regression coefficients?\n- How do the standard GLM assumptions (LINE) apply when working with categorical predictors?\n- How does the GLM formulation and interpretation change when including one vs. two categorical predictors, especially regarding main effects and interactions?\n- What does a significant interaction term in a GLM tell us about the relationship between categorical predictors?\n- Why are post-hoc tests necessary for interpreting GLMs with significant categorical predictors with more than two levels?\n\n# Thanks!\n\nThis presentation is based on the [SOLES Quarto reveal.js template](https://github.com/usyd-soles-edu/soles-revealjs) and is licensed under a [Creative Commons Attribution 4.0 International License][cc-by].\n\n\n<!-- Links -->\n[cc-by]: http://creativecommons.org/licenses/by/4.0/",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}