project:
  render:
    - "index.qmd"
    - "lectures/L00-welcome-to-beda/index.qmd"
    - "lectures/L01-intro-exp-design-analysis/index.qmd"
    - "lectures/L02a-representative-sampling/index.qmd"
    - "lectures/L02b-linear-model/index.qmd"
    - "lectures/L02c-all-linear-model/index.qmd"
    - "lectures/L03a-model-appropriate/index.qmd"
    - "lectures/L03b-ttests/index.qmd"
    - "lectures/L04a-mlr/index.qmd"
    - "lectures/L04b-anova/index.qmd"
    - "lectures/L04c-model-transformations/index.qmd"
  resources:
    - "lectures/L03a-model-appropriate/slides.pdf"
    - "lectures/L03a-model-appropriate/slides-solarized.pdf"
    - "lectures/L03b-ttests/slides.pdf"
    - "lectures/L03b-ttests/slides-solarized.pdf"
